### ISSUE TITLE
multiple-value gossie.NewMapping() in single-value context

### ISSUE THREAD

**Issue by andoriyu** [carloscm/gossie#14]
I'm trying to run code from example for mapping and keep getting:

`multiple-value gossie.NewMapping() in single-value context`

**Comment by carloscm** [comment]
You are right, the README was wrong. NewMapping returns 2 values, the mapping and an a error value. I've fixed the docs.

**Comment by andoriyu** [comment]
oh, i knew something is missing, why didn't I see that. Thank you.
