### ISSUE TITLE
Auth support?

### ISSUE THREAD

**Issue by cespare** [carloscm/gossie#4]
Is it possible to pass in credentials through gossie? Doesn't seem like it is, but it is in the generated thrift. Maybe it's easy to add.

**Comment by carloscm** [comment]
I've added a new field in PoolOptions, named Authentication. It's a map[string]string than when having one or more items will make login() to be called before set_keyspace(), with the same contents as in Authentication. Tell me if it works for you!

**Comment by cespare** [comment]
Hey @carloscm thanks for taking care of this.

I haven't had a chance to try it out, but I'll let you know when I do. :+1:
